kind: Deployment
metadata:
  name: solar-system
  labels:
    app: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - name: solar-system
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
